### ISSUE TITLE
Cync Motion + Dimmer (no neutral) switches failing after upgrade to latest release

### ISSUE THREAD

**Issue by Anon666333** [nikshriv/cync_lights#45]
I have two Motion activated Dimmer switches (no neutral) from Cync. These were working fine prior to upgrading. After upgrading, they no longer connect, but they are connected to the WiFi and bluetooth on my phone.
See below the slightly uninformative error message:

`2023-02-13 14:58:50.321 ERROR (MainThread) [homeassistant.components.light] Error while setting up cync_lights platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/cync_lights/light.py", line 23, in async_setup_entry
    if not hub.cync_rooms[room]._update_callback and (room in config_entry.options["rooms"] or room in config_entry.options["subgroups"]):
KeyError: 'subgroups'
2023-02-13 14:58:50.504 ERROR (Thread-2 (_start_tcp_client)) [custom_components.cync_lights.cync_hub] ShuttingDown: `

**Comment by nikshriv** [comment]
Try deleting your current configuration and then signing back in.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Anon666333 ***@***.***>
Sent: Monday, February 13, 2023 12:05:05 PM
To: nikshriv/cync_lights ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nikshriv/cync_lights] Cync Motion + Dimmer (no neutral) switches failing after upgrade to latest release (Issue #45)


I have two Motion activated Dimmer switches (no neutral) from Cync. These were working fine prior to upgrading. After upgrading, they no longer connect, but they are connected to the WiFi and bluetooth on my phone.
See below the slightly uninformative error message:

2023-02-13 14:58:50.321 ERROR (MainThread) [homeassistant.components.light] Error while setting up cync_lights platform for light Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform await asyncio.shield(task) File "/config/custom_components/cync_lights/light.py", line 23, in async_setup_entry if not hub.cync_rooms[room]._update_callback and (room in config_entry.options["rooms"] or room in config_entry.options["subgroups"]): KeyError: 'subgroups' 2023-02-13 14:58:50.504 ERROR (Thread-2 (_start_tcp_client)) [custom_components.cync_lights.cync_hub] ShuttingDown:

**Comment by Anon666333** [comment]
If only I thought of that....thanks mate, worked perfectly!
I see the removal of the motion sensors from the no-neutral config - thank you! Removes any confusion.

Great work on this integration, much appreciated!
