### ISSUE TITLE
Entry Loading Error

### ISSUE THREAD

**Issue by tate-christians** [nikshriv/cync_lights#48]
I have been trying to connect my Cync bulbs to home assistant all day, but i am getting a few errors when i try to configure. I’ve been looking around and can’t find a solution to these problems. Maybe you can take a look?

Here is the error log:
`2023-02-27 10:14:57.426 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry cync_lights_EMAIL for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 533, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 175, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 181, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2023-02-27 10:14:57.429 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry cync_lights_EMAIL for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 533, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 89, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 181, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!`

**Comment by nikshriv** [comment]
The recent change is the cause. I'm reverting back until I can get the change wiring properly.

**Comment by tate-christians** [comment]
Thank you. Hopefully once you revert it will work. I'll reconfigure once code is available

**Comment by tate-christians** [comment]
It works! Thank you for making that change!
