### ISSUE TITLE
Errored out after downloading update

### ISSUE THREAD

**Issue by Vapurade** [nikshriv/cync_lights#56]
Was getting “unknown error” trying to configure the integration after moving to latest version (coming from one of the very first versions) I then did a clean download and reinstall, now on the screen where you select devices it throws “Unknown Error Occurred” after clicking “submit” and it even does it with nothing selected.

**Comment by Vapurade** [comment]
Pretty much tried everything i can think of outside of installing a fresh copy of HA. I only know VB so I'm not exactly sure what that error means, but I'm assuming the object isn't declared or is missing? Maybe i will spin up a fresh vm and try that incase i have a corrupted fire or something. 

This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/cync_lights/config_flow.py:162
Integration: Cync Lights (documentation)
First occurred: 10:27:20 PM (11 occurrences)
Last logged: 10:30:29 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 67, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 271, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/cync_lights/config_flow.py", line 122, in async_step_select_switches
    return await self._async_finish_setup()
  File "/config/custom_components/cync_lights/config_flow.py", line 162, in _async_finish_setup
    return self.hass.config_entries.async_abort(reason="reauth_successful")
AttributeError: 'ConfigEntries' object has no attribute 'async_abort'

**Comment by nikshriv** [comment]
Did you delete your old configuration before downloading the newest version? It looks like it may be failing because it still has your old configuration. You might try insisting the old version again, then delete your old configuration and then reinstall the latest version.

**Comment by Vapurade** [comment]
I that was it.. thanks for the help! The new features are awesome, great work!
