### ISSUE TITLE
Getting "ShuttingDown:" after authorizing, devices do nothing when controlled via HA

### ISSUE THREAD

**Issue by iReadTOS** [nikshriv/cync_lights#60]
Hello all,
I have two wifi outdoor plugs, which work fine via the Cync app (when it works). This plugin was working fine last week on my Raspberry Pi 3b+ before I moved to an x64 laptop (I'm on HAOS). After installing this via HACS and authorizing, my devices show up, but do nothing when manipulated via HA. The only error I see in the logs is this:

**Comment by jloberg1** [comment]
I back up this issue:
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for cync_lights using this method at custom_components/cync_lights/__init__.py, line 19: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

**Comment by RickyTickyTshirt** [comment]
Single device on this productct.  Integration once loaded, authorized & HA restarted the (switch) does showup.  However turning on or off from with in HA does not cause the switch any action.  Log of an event.
_________________________
ConnectionResetError: Connection lost
2023-09-21 13:40:28.400 WARNING (Thread-111 (_start_tcp_client)) [asyncio] SSL connection is closed
2023-09-21 13:40:28.404 ERROR (Thread-111 (_start_tcp_client)) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/cync_lights/cync_hub.py", line 298, in send
    await self.writer.drain()
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 378, in drain
    await self._protocol._drain_helper()
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 167, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost

_________________________
Help appreciated.
